-- Estructura recomendada para adaptar TuPista a la corrección del tutor.
-- Ejecutar en el SQL Editor de Supabase y revisar nombres si tu BD usa columnas distintas.

create table if not exists clubes (
    id bigint generated by default as identity primary key,
    nombre text not null unique,
    direccion text default '',
    telefono text default '',
    imagen text default ''
);

-- Si ya tienes pistas con una columna de texto llamada club, primero se crean los clubes.
insert into clubes (nombre)
select distinct club
from pistas
where club is not null and club <> ''
on conflict (nombre) do nothing;

-- Pistas: cada pista pertenece a un único club.
alter table pistas add column if not exists "clubId" bigint;

update pistas p
set "clubId" = c.id
from clubes c
where p.club = c.nombre
  and p."clubId" is null;

do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'pistas_clubid_fkey') then
        alter table pistas
            add constraint pistas_clubid_fkey
            foreign key ("clubId") references clubes(id) on delete restrict;
    end if;
end $$;

-- Reservas: se elimina la información repetida del club. El club se obtiene por Reserva -> Pista -> Club.
-- Antes de borrar la columna antigua, comprueba que la app ya usa clubId en pistas.
-- alter table reservas drop column if exists club;

-- Reseñas: ahora relacionan Usuario y Club.
alter table resenas add column if not exists "clubId" bigint;

update resenas r
set "clubId" = c.id
from clubes c
where r.club = c.nombre
  and r."clubId" is null;

do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'resenas_clubid_fkey') then
        alter table resenas
            add constraint resenas_clubid_fkey
            foreign key ("clubId") references clubes(id) on delete cascade;
    end if;
end $$;

-- Un usuario solo puede publicar una reseña por club.
create unique index if not exists resenas_usuario_club_unique
on resenas ("usuarioId", "clubId");

-- Cuando verifiques que todo funciona, puedes eliminar las columnas antiguas para evitar inconsistencias:
-- alter table pistas drop column if exists club;
-- alter table resenas drop column if exists club;
